### PR TITLE
Updated the dead maven repo

### PR DESCRIPTION
**Pull request by jingwenMC**
The maven repo seemed to be dead. I've moved it to Jitpack and made several changes to make it usable again.

### CODE REVIEW

**Comment by dgrfps** [comment]
THANKS FOR KEEPING IT ALIVE!

**Comment by TigerHix** [comment]
Latest maven run failed:
https://github.com/TigerHix/ScoreboardLib/actions/runs/3797212336

@jingwenMC Could you help check why?

**Comment by dgrfps** [comment]
Are you trying to upload the library to his repository?
the build error is on upload, I can't read the full log

**Comment by dgrfps** [comment]
Yes that's probably it, check your action yml, it is trying to upload to his repository, which you don't have access

**Comment by TigerHix** [comment]
Reverted #9. Let me know when you have fixed the repo issue. For this public repo I don't think you should include a workflow action to upload to any repo.

Thanks @dgrfps for the heads up.

**Comment by dgrfps** [comment]
No problem @TigerHix, i created a pull req in case you wan't to merge.   
I compiled using compile & package script, both passing.
I setted maven/readme to use @jingwenMC repository.

**Comment by jingwenMC** [comment]
> Latest maven run failed: https://github.com/TigerHix/ScoreboardLib/actions/runs/3797212336
> 
> @jingwenMC Could you help check why?

It attempts to upload the artifact to my maven repo :(

**Comment by jingwenMC** [comment]
> Reverted #9. Let me know when you have fixed the repo issue. For this public repo I don't think you should include a workflow action to upload to any repo.
> 
> Thanks @dgrfps for the heads up.

It should be fixed in #12

**Pull request merged**
